package mk.ukim.finki.emt.appointmentmanagement.domain.model;

public enum AppointmentType {
    GENERAL_CHECK_UP,
    SPECIALIST_CONSULTATION,
    FOLLOW_UP_APPOINTMENT,
    PREOPERATIVE_APPOINTMENT,
    POSTOPERATIVE_APPOINTMENT,
    WELL_WOMAN_VISIT,
    WELL_CHILD_VISIT,
    VACCINATION_APPOINTMENT,
    CHRONIC_DISEASE_MANAGEMENT,
    MENTAL_HEALTH_APPOINTMENT,
    EMERGENCY_ROOM_VISIT,
    PREVENTIVE_CARE_APPOINTMENT,
    ALLERGY_TESTING_APPOINTMENT,
    PHYSICAL_THERAPY_APPOINTMENT,
    OCCUPATIONAL_THERAPY_APPOINTMENT
}
